import axios from "axios";

export default axios.create({
  method: "GET",
  headers: {
    Authorization:
      "Bearer v2/ZHNwOGh4Z09BQVFOd2FtTWpORkhldlUwZDZGcnkzWWwvMTg2NDEwOTkyL2N1c3RvbWVyLzQvZHZuTmxwNHJJaXZILVllWGdPZXlTaGRmX24xcTM4Z1lwVVVTdVZoa3J4RzVGSW9RX3BYaXBaNGpsVE9LSnNNMmZfaFZHaDI1OWRJNVFNMmEwZFk3UlJUVGVCbWNqczd0aDR2MmppMEJ3eEhVSzBya0hvOGJJSFJtVzJ6TG1UQTRTd0hVVmc0YS1LSkZJWHhFNUVFRFlEUUdWTW5YbjJZTzdmZFRlOFdJakN3bnNkb3V0T2dkNGpQVWo2ZVZZMEN3bC1TTFEtNzFNR0RSWllkaXl5T0hFUS9OZ1k4S2M4MVJycGFoTE5SMjMxa0ZR",
  },
});
